version: '3.3'
services:

  mongo:
    image: mongo
    container_name: todolist_db
    restart: always
    environment:
      MONGO_DATA_DIR: /data/db
    volumes:
    - ./data/db:/data/db
    ports:
    - 27017:27017

  backend:
    build: ./backend
    ports:
    - 8080:8080
    links:
    - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/todo-list

  angular:
    image: node:8.1.3
    volumes:
    - ./frontend:/frontend
    working_dir: /frontend
    expose:
    - 4200
    ports:
    - 4200:4200
    command: /bin/bash -c "npm start"
